name: build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.6.0

      - name: "Install dependencies"
        run: npm install

      - name: "Build cjs"
        run: npm run buildcjs

      - name: "Build esm"
        run: npm run buildesm

